### ISSUE TITLE
bug: cant expand folders dropdown on workspace sidebar without navigating to the folder page. 

### ISSUE THREAD

**Issue by ovirandunu** [bynery-main/limonata-notion-clone#166]
make it possible

**Comment by NatanAmado** [comment]
That's how it should behave. In what situation would want to not navigate to the folder you're opening

**Comment by ovirandunu** [comment]
If you want to expand the folders dropdown and view the files in the dropdown while working on a file in a different folder or even within it (among many other edge cases like this).  @NatanAmado please establish this functionality

**Comment by NatanAmado** [comment]
@ovirandunu Currently, clicking the folder on the workspace sidebar is the **only way** to navigate to that folder. The only way of allowing this without rethinking the whole navigation flow would be to, for example, not navigate to a folder while "shift" is pressed. Not a fan of this kind of solution but it seems like the only plausible one and like you say, it is an edge case.

**Comment by ovirandunu** [comment]
@NatanAmado make it expand on first click and navigate on second

**Comment by NatanAmado** [comment]
@ovirandunu It's going to make it unintuitive for the 99% of people who'll just want to navigate to a folder just to satisfy a 1% of cases in which (for some reason) you'd really want to see the contents of other folders without navigating to it.

**Comment by ovirandunu** [comment]
Bro pls just fix it it's retarded like this

**Comment by ovirandunu** [comment]
@noahlabear wdyt?

**Comment by noahlabear** [comment]
I think we can make it so that when the dropdown arrow is pressed next folder name, it drops down without redirecting. When the three dots are clicked it should also dropdown the rename and delete without navigating to the folder. When any other area of the topic is pressed, then redirect.

This must be implemented like this imo as otherwise we wouldn't need a dropdown in the first place.

Best of luck @NatanAmado
